- id: '1680818984534'
  alias: ChangeLightState
  description: ''
  trigger:
  - platform: event
    event_type: rhasspy_ChangeLightState
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: hermes/dialogueManager/endSession
      payload_template: '{"sessionId": "{{trigger.event.data._intent.sessionId}}",
        text" : "ok"}'
  - service_template: light.turn_{{trigger.event.data.state}}
    data:
      entity_id: light.{{trigger.event.data.name.replace(' ', '_')}}
  mode: single
- id: '1680916818783'
  alias: Pause
  description: ''
  trigger:
  - platform: event
    event_type: rhasspy_PauseMusic
  condition: []
  action:
  - service: media_player.media_pause
    data: {}
    target:
      entity_id: media_player.spotify
  mode: single
- id: '1680917001630'
  alias: PlayMusic
  description: ''
  trigger:
  - platform: event
    event_type: rhasspy_PlayMusic
  condition: []
  action:
  - service: media_player.media_play
    data: {}
    target:
      entity_id: media_player.spotify
  mode: single
