
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

api:

snips:

intent_script:
  ChangeLightState:  # Intent type
    action:
      # - service: mqtt.publish
      #   data:
      #     payload_template: '{"sessionId": "{{_intent.sessionId}}", "text" : "ok, {{name}} has been turned {{state}}"}'
      #     topic: hermes/dialogueManager/endSession
      - service_template: light.turn_{{state}}
        data:
          entity_id: light.{{name.replace(' ', '_')}}
