
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

snips:

intent_script:
  GetTemperature:  # Intent type
    speech:
      text: Hello from Home Assistant!
    action:
      service: system_log.write
      data:
        message: Hello from an intent!
