version: "3.9"

services:
  mqtt:
    build: ./mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt-data/config:/mosquitto/config
      - ./mqtt-data/data:/mosquitto/data
      - ./mqtt-data/log:/mosquitto/log
  hass:
    build: ./hass
    ports:
      - "8123:8123"
    volumes:
      - ./hass-data/config:/config
  rhasspy:
    build: ./rhasspy
    restart: unless-stopped
    ports:
        - "12101:12101"
    volumes:
      - ./rhasspy-data/profiles:/profiles
      - /etc/localtime:/etc/localtime:ro
    #  - ~/.config/pulse:/root/.config/pulse
    environment:
      - PULSE_SERVER=host.docker.internal
    command: --user-profiles /profiles --profile en

